//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.13 at 04:01:56 p. m. CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.htc.com/calculatorservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.htc.calculatorservice;
